module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'secondary-fixed-dim': '#dcc800',
        background: '#fbf9f9',
        'tertiary-container': '#f8feff',
        'on-surface': '#1b1c1c',
        'surface-container-highest': '#e3e2e2',
        'on-primary-container': '#75756e',
        'surface-container': '#efeded',
        secondary: '#695f00',
        'on-error': '#ffffff',
        'primary-container': '#fffdf5',
        'primary-fixed': '#e4e3db',
        'on-background': '#1b1c1c',
        'error-container': '#ffdad6',
        tertiary: '#5f5e5e',
        'on-tertiary-fixed': '#1c1b1b',
        'tertiary-fixed': '#e5e2e1',
        'inverse-on-surface': '#f2f0f0',
        'surface-container-high': '#e9e8e7',
        'on-tertiary-fixed-variant': '#474746',
        'on-secondary-container': '#706500',
        'on-surface-variant': '#474741',
        'outline-variant': '#c8c7be',
        'on-tertiary': '#ffffff',
        'surface-tint': '#5f5f59',
        'surface-dim': '#dbdad9',
        'secondary-container': '#fae519',
        outline: '#777770',
        'inverse-primary': '#c8c7bf',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#474742',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#c8c7bf',
        'on-error-container': '#93000a',
        'inverse-surface': '#303031',
        'on-secondary-fixed': '#201c00',
        surface: '#fbf9f9',
        primary: '#5f5f59',
        'on-secondary-fixed-variant': '#4f4800',
        'on-primary-fixed': '#1b1c17',
        'surface-variant': '#e3e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-bright': '#fbf9f9',
        'secondary-fixed': '#fae519',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
      },
      spacing: {
        'margin-mobile': '20px',
        'container-max': '1280px',
        unit: '8px',
        'margin-desktop': '64px',
        gutter: '24px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};